import type { Metadata } from "next";
import { SidebarProvider } from "./components/ui/sidebar";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppSidebar } from "./components/AppSidebar/AppSidebar";
import { SidebarNav } from "./components/SidebarNav/SidebarNav";
import { SidebarWrapper } from "./components/SidebarWrapper/SidebarWrapper";
import { Navbar } from "./components/Navbar/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bubble Transparent Sea",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarWrapper>
          <div className="w-full h-screen bg-[url('/bg.webp')] bg-cover bg-center relative overflow-hidden">
            <div className="absolute top-0 bottom-0 left-0 right-0 bg-opacity-20 bg-black">
              <Navbar />
              {children}
            </div>
          </div>
        </SidebarWrapper>
      </body>
    </html>
  );
}
